### ISSUE TITLE
"Failed to show URI:http://localhost:9000" on headless server

### ISSUE THREAD

**Issue by medined** [overview/overview-server#615]
After a long time of compiling, the ./dev command showed the following exception on a headless Ubuntu virtual machine. I feel an echo comment about the URL would be better than trying to open a browser.

```
[overview-server] (Server started, use Ctrl+D to stop and go back to the console...)
[overview-server]
[error] (Thread-4) java.io.IOException: Failed to show URI:http://localhost:9000
java.io.IOException: Failed to show URI:http://localhost:9000
	at sun.awt.X11.XDesktopPeer.launch(XDesktopPeer.java:114)
	at sun.awt.X11.XDesktopPeer.browse(XDesktopPeer.java:98)
	at java.awt.Desktop.browse(Desktop.java:386)
	at org.overviewproject.runner.BrowserLauncher.maybeOpenBrowserToUrl(BrowserLauncher.scala:34)
	at org.overviewproject.runner.BrowserLauncher$$anon$1.run(BrowserLauncher.scala:40)
	at java.lang.Thread.run(Thread.java:744)
[trace] Stack trace suppressed: run last runner/compile:run for the full output.
```

**Comment by adamhooper** [comment]
We don't auto-open the URL any more. If we did, we wouldn't do it with Java. So this bug won't crop up again.
