### ISSUE TITLE
Can't run on Lubuntu 15.04

### ISSUE THREAD

**Issue by hpiedcoq** [overview/overview-server#638]
Hi!

I religiously followed every steps written on the howto but i can't manage to run Overview.

Here is the error : 

Exception in thread "main" java.lang.Exception: Could not find Postgres 9.0-9.3. Please install initdb, postgres (which must be executable) in one of: /usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /usr/games, /usr/local/games, /usr/sbin, /usr/local/sbin, /usr/lib/postgresql/9.3/bin, /usr/lib/postgresql/9.2/bin, /usr/lib/postgresql/9.1/bin, /usr/lib/postgresql/9.0/bin, /usr/bin, /usr/local/bin, /usr/local/pgsql/bin, /opt/local/lib, /opt/local/lib/postgresql93/bin, /opt/local/lib/postgresql92/bin, /opt/local/lib/postgresql91/bin, /opt/local/lib/postgresql90/bin, /Applications/Postgres.app/Contents/MacOS/bin, /Applications/Postgres93.app/Contents/MacOS/bin, /Applications/Postgres.app/Contents/Versions/9.3/bin, /sw/opt/postgresql-9.3/bin, /sw/opt/postgresql-9.2/bin, /sw/opt/postgresql-9.1/bin, /sw/opt/postgresql-9.0/bin, /opt/PostgreSQL/9.3/bin, /opt/PostgreSQL/9.2/bin, /opt/PostgreSQL/9.1/bin, /opt/PostgreSQL/9.0/bin, /Library/PostgreSQL/9.3/bin, /Library/PostgreSQL/9.2/bin, /Library/PostgreSQL/9.1/bin, /Library/PostgreSQL/9.0/bin
	at org.overviewproject.runner.commands.PostgresCommand$$anonfun$apply$3.apply(PostgresCommand.scala:109)
	at org.overviewproject.runner.commands.PostgresCommand$$anonfun$apply$3.apply(PostgresCommand.scala:109)
	at scala.util.Either.fold(Either.scala:97)
	at org.overviewproject.runner.commands.PostgresCommand$.apply(PostgresCommand.scala:108)
	at org.overviewproject.runner.commands.PostgresCommand$.apply(PostgresCommand.scala:96)
	at org.overviewproject.runner.Database$$anon$1.<init>(Database.scala:143)
	at org.overviewproject.runner.Database.<init>(Database.scala:142)
	at org.overviewproject.runner.Main.maybeWithDatabase$1(Main.scala:165)
	at org.overviewproject.runner.Main.run(Main.scala:191)
	at org.overviewproject.runner.Main$.main(Main.scala:253)
	at org.overviewproject.runner.Main.main(Main.scala)

Any hint?

Thanks

**Comment by hpiedcoq** [comment]
oups wrong path. Sorry.
